//! Animation demo (stage 1 acceptance): programmatically generate a set of "slide + stationary
//! segment" placeholder frames (no real AI image generation needed), run vitric assets --frames
//! to produce an atlas + animation config + BC7 compression, then boot the engine to self-check
//! playback.
//!
//! **Test purity**: builds a working project entirely inside a temp directory (read-only copy of
//! the project template from examples/frame-anim; artifacts are generated in the temp dir), and
//! **never writes to the source tree** — otherwise it would collide with other "read examples"
//! tests running in parallel on half-written artifacts (this once caused a flaky first-run
//! failure). examples/frame-anim is a stable fixture committed to git (pre-generated artifacts);
//! it is produced once by `vitric assets --frames` and not rebuilt at test runtime.
//!
//! Acceptance checklist (design-frame-animation.md section 5 stage 1):
//! - A sequence of images → --frames produces atlas + config ✓ (this test generates in a temp
//!   dir)
//! - Engine playback correctness (frame order, stay, trim placement) ✓ (advance_animations
//!   self-check)
//! - VRAM measured comparison (RGBA8 vs BC7 multiple) ✓ (report's compression_ratio)
//! - check verifies artifacts ✓ (run check once on the temp project to confirm green)

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde_json::json;

use vitric_cli::frames::{self, FramesOptions};
use vitric_cli::runtime::{self, advance_animations};
use vitric_data::Clip;
use vitric_ecs::World;

/// Read-only template source of examples/frame-anim (project files, no artifacts).
fn template_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../examples/frame-anim")
}

/// Copy the demo project's **project files** (excluding assets/ and animations.json artifacts)
/// into the temp working directory.
/// Artifacts are generated by the test running --frames inside the working directory — the
/// working directory is temp, the source tree is untouched.
fn setup_work_project(work: &Path) {
    let tpl = template_dir();
    for rel in ["vitric.json", "schema.json", "scenes/main.json", "rules/game.json"] {
        let dst = work.join(rel);
        std::fs::create_dir_all(dst.parent().unwrap()).unwrap();
        std::fs::copy(tpl.join(rel), &dst).unwrap();
    }
    // --frames writes artifacts into the project assets/, the directory must exist first (the
    // original examples version implicitly had it)
    std::fs::create_dir_all(work.join("assets")).unwrap();
}

fn write_png(path: &Path, w: u32, h: u32, rgba: &[u8]) {
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    let file = std::fs::File::create(path).unwrap();
    let mut enc = png::Encoder::new(std::io::BufWriter::new(file), w, h);
    enc.set_color(png::ColorType::Rgba);
    enc.set_depth(png::BitDepth::Eight);
    enc.write_header().unwrap().write_image_data(rgba).unwrap();
}

/// Programmatically generate 10 frames: an 8x8 square slides from left to right; the middle 3
/// frames (4,5,6) keep position+color unchanged (stationary segment, tests dedup); the square is
/// drawn on a transparent background (tests trim). Same-size 32x32 input.
fn generate_source_frames(dir: &Path) {
    let (w, h) = (32u32, 32u32);
    for i in 0..10u32 {
        let mut px = vec![0u8; (w * h * 4) as usize]; // transparent background
        let step = if i <= 4 {
            i
        } else if i <= 6 {
            4 // stationary segment: position does not move
        } else {
            i - 2
        };
        let bx = 2 + step * 2;
        let by = 12u32;
        let cstep = if (4..=6).contains(&i) { 4 } else { i.min(9) };
        let r = (40 + cstep * 20) as u8;
        for yy in by..by + 8 {
            for xx in bx..bx + 8 {
                if xx < w && yy < h {
                    let o = ((yy * w + xx) * 4) as usize;
                    px[o..o + 4].copy_from_slice(&[r, 80, 200, 255]);
                }
            }
        }
        write_png(&dir.join(format!("frame{i:02}.png")), w, h, &px);
    }
}

/// Generate demo artifacts (temp dir) + self-check engine playback + check green.
#[test]
fn frame_anim_demo_pipeline_and_playback() {
    // Working project + source frames are all in the temp dir (process-id-isolated for parallel
    // instances), not touching the source tree
    let work = std::env::temp_dir().join(format!("vitric-frameanim-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&work);
    let project = work.join("project");
    setup_work_project(&project);

    // 1. Programmatically generate source sequence frames into the temp dir (source frames do
    // not enter the project, only the artifacts do)
    let seq = work.join("src/slide"); // dir name = clip name
    std::fs::create_dir_all(&seq).unwrap();
    generate_source_frames(&seq);

    // 2. Run --frames: produce atlas + config + BC7
    let report =
        frames::run(&project, &seq, &FramesOptions { colors: 16, compress: true }).unwrap();
    assert_eq!(report.input_frames, 10);
    assert_eq!(report.kept_frames, 8, "中间 3 帧静止 → 去重砍到 8 帧");
    let ratio = report.atlas_raw_bytes as f64 / (report.bc7_bytes.unwrap() - 20) as f64;
    assert!((ratio - 4.0).abs() < 0.01, "BC7 块数据是 RGBA8 的 1/4（4×），实测 {ratio}");

    // trim takes effect: each frame's post-crop width/height is the content bounding box (≤ input
    // 32x32)
    for r in &report.records {
        assert!(r.atlas_rect.2 <= 32 && r.atlas_rect.3 <= 32, "trim 后不超原尺寸");
        assert!(r.atlas_rect.2 > 0 && r.atlas_rect.3 > 0, "内容帧裁后非空");
    }

    // 3. Engine self-check: play "slide" with the project's assembled runtime, advancing frame by
    // tick
    let (mut sim, mut rt) = runtime::Runtime::boot(&project).expect("demo 项目应能启动");
    let actor = sim.world.entity("actor").expect("场景里有 actor");
    let mut frames_seen = Vec::new();
    for _ in 0..report.records.iter().map(|r| r.stay).sum::<u32>() {
        advance_animations(&mut sim.world, &rt.animations).unwrap();
        frames_seen
            .push(sim.world.get_field(actor, "Sprite.image").unwrap().as_str().unwrap().to_string());
        let _ = &mut rt;
    }
    // Playback sequence = the frame order expanded from the config (stay = repeated frame name),
    // deterministic per frame
    let anims: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(project.join("animations.json")).unwrap(),
    )
    .unwrap();
    let expanded: Vec<String> = anims["clips"]["slide"]["frames"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(frames_seen, expanded, "引擎逐 tick 播放 = 配置展开帧序（帧序+停留对）");

    // The stationary segment shows up in the expanded sequence as consecutive identical frame
    // names (stay placement)
    let has_run = expanded.windows(2).any(|w| w[0] == w[1]);
    assert!(has_run, "静止段应展开成连续相同帧（停留）");

    // 4. check verifies artifacts are green (atlas exists, frame table valid, uv not out of
    // bounds, frame image references consistent)
    runtime::check(&project).expect("demo 产物 check 该过");

    // 5. Determinism: run --frames again, animations.json is byte-identical
    let before = std::fs::read(project.join("animations.json")).unwrap();
    frames::run(&project, &seq, &FramesOptions { colors: 16, compress: true }).unwrap();
    let after = std::fs::read(project.join("animations.json")).unwrap();
    assert_eq!(before, after, "同输入 --frames 产物逐字节一致");

    // The engine can also play with the generated clip (fed directly to advance_animations,
    // independent of the scene)
    let clip: Clip = serde_json::from_value(anims["clips"]["slide"].clone()).unwrap();
    let clips = BTreeMap::from([("slide".to_string(), clip)]);
    let mut w = World::new();
    let e = w.spawn();
    w.set_component(e, "Sprite", json!({"w": 1.0, "h": 1.0, "color": "#fff", "image": ""})).unwrap();
    w.set_component(e, "Anim", json!({"clip": "slide", "prev": "", "t": 0, "done": false})).unwrap();
    advance_animations(&mut w, &clips).unwrap();
    assert_eq!(
        w.get_field(e, "Sprite.image").unwrap().as_str().unwrap(),
        expanded[0],
        "首 tick 播第一帧"
    );

    let _ = std::fs::remove_dir_all(&work);
}
