// HUD decoration — food progress bar.
// Colony.food_i is the current food amount (0..100); every frame we compute a 10-cell bar string,
// write it to Colony.food_bar, and the rule in rules/hud.json pulls this string straight into @hud_food_lbl.UiLabel.content.
// Unicode half-block characters (█ filled / ░ light) replace bare digits, so the food level is visible at a glance.
//
// Systems:
//   food-bar     Colony → Colony.food_bar (pure string, no side effects, deterministic)

const FOOD_BAR_CELLS = 10;     // total bar cells
const FOOD_BAR_FILLED = "\u2588"; // █
const FOOD_BAR_EMPTY  = "\u2591"; // ░

vitric.system("food-bar", { query: ["Colony"], writes: ["Colony"] }, (entities, ctx) => {
  for (const e of entities) {
    const food = Math.round(e.Colony.food_i || 0);
    const clamped = food < 0 ? 0 : (food > 100 ? 100 : food);
    const filled = Math.round((clamped / 100) * FOOD_BAR_CELLS);
    let bar = "";
    for (let i = 0; i < FOOD_BAR_CELLS; i++) {
      bar += i < filled ? FOOD_BAR_FILLED : FOOD_BAR_EMPTY;
    }
    e.Colony.food_bar = "食 " + clamped + "/100 [" + bar + "]";
  }
});

// Flare warning bar: shows a warning string when Colony.flare_warning == 1.
// The rule in hud.json pulls Colony.flare_bar into @flare_lbl.UiLabel.content.
// @flare_lbl entity is added in Task 9 scene polish; until then the rule's set silently no-ops.
vitric.system("flare-bar", { query: ["Colony"], writes: ["Colony"] }, (entities, ctx) => {
  for (const e of entities) {
    const warn = e.Colony.flare_warning | 0;
    e.Colony.flare_bar = warn ? "\u26a0 \u8000\u6591\u5373\u5c06\u6765\u88ad!" : "";
  }
});

// 7-day weather forecast. Updates once per day (not every tick) to avoid flicker.
// Uses ctx.random_stream("forecast") for deterministic generation — the forecast for
// day N is the same regardless of when it's generated (replay-stable via E3 substream).
//
// The forecast is a PREDICTION based on seasonal weather weights — it doesn't match the
// actual weather (which is generated by weather-tick using a separate substream). The
// forecast gives the player a rough outlook for planning.
//
// SEASONAL_WEIGHTS is duplicated from flare.js (the weather-tick system). Extracting to
// a shared module is out of scope — the weights are stable and the duplication is noted.

const FORECAST_DAYS = 7;

const FORECAST_SEASONAL_WEIGHTS = {
  spring: { clear: 50, cloudy: 30, rain: 15, storm: 5, flare: 0 },
  summer: { clear: 40, cloudy: 20, rain: 10, storm: 5, flare: 25 },
  autumn: { clear: 45, cloudy: 30, rain: 20, storm: 5, flare: 0 },
  winter: { clear: 30, cloudy: 40, rain: 0, storm: 30, flare: 0 }
};

const FORECAST_LABELS = {
  clear: "晴", cloudy: "阴", rain: "雨", storm: "暴风", flare: "耀斑"
};

function forecastPick(stream, weights) {
  const total = Object.values(weights).reduce((a, b) => a + b, 0);
  const r = stream.next() * total;
  let acc = 0;
  for (const [k, w] of Object.entries(weights)) {
    acc += w;
    if (r < acc) return k;
  }
  return Object.keys(weights)[0];
}

vitric.system("forecast-update", { query: ["Clock", "Season", "Forecast"], writes: ["Forecast"] }, (entities, ctx) => {
  for (const e of entities) {
    // Only regenerate when the day changes — not every tick.
    if (e.Clock.day === e.Forecast.last_day) continue;

    const stream = ctx.random_stream("forecast");
    const season = e.Season.current;
    const weights = FORECAST_SEASONAL_WEIGHTS[season] || FORECAST_SEASONAL_WEIGHTS.spring;

    // Generate 7 weather labels for the next 7 days.
    const labels = [];
    for (let i = 0; i < FORECAST_DAYS; i++) {
      const w = forecastPick(stream, weights);
      labels.push(FORECAST_LABELS[w] || w);
    }

    e.Forecast.days = "预报: " + labels.join(" ");
    e.Forecast.last_day = e.Clock.day;
  }
});